Correct filename in library.properties includes field
The includes field in library.properties is used to add an #include directive to the sketch via Sketch > Include Library > LIS3DH motion detection. The incorrect filename caused compilation to fail:

error: LIS3DH motion detection.h: No such file or directory

 #include <LIS3DH motion detection.h>

          ^~~~~~~~~~~~~~~~~~~~~~~~~~~